services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongo_db
    ports:
      - "2700:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=martel
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8000:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=martel
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}